version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: slackmm2
      POSTGRES_USER: slackmm2
      POSTGRES_PASSWORD: slackmm2
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U slackmm2"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      DATABASE_URL: postgresql://slackmm2:slackmm2@db:5432/slackmm2
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
      - ../infra:/infra
      - ../alembic.ini:/alembic.ini
    restart: always

volumes:
  db_data: 