// This file is automatically generated. Do not modify it manually.

package main

import (
	"encoding/json"
	"strings"

	"github.com/mattermost/mattermost/server/public/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "mm-importer",
  "name": "MM Importer",
  "description": "Import messages and metadata from external sources as any user.",
  "homepage_url": "https://github.com/mattermost/mattermost-plugin-starter-template",
  "support_url": "https://github.com/mattermost/mattermost-plugin-starter-template/issues",
  "icon_path": "assets/starter-template-icon.svg",
  "version": "0.3.0",
  "min_server_version": "6.0.0",
  "server": {
    "executables": {
      "linux-amd64": "server/dist/plugin-linux-amd64"
    },
    "executable": ""
  },
  "settings_schema": {
    "header": "",
    "footer": "",
    "settings": [],
    "sections": null
  }
}
`

func init() {
	_ = json.NewDecoder(strings.NewReader(manifestStr)).Decode(&manifest)
}
