// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "mm-importer",
    "name": "MM Importer",
    "description": "Import messages and metadata from external sources as any user.",
    "homepage_url": "https://github.com/mattermost/mattermost-plugin-starter-template",
    "support_url": "https://github.com/mattermost/mattermost-plugin-starter-template/issues",
    "icon_path": "assets/starter-template-icon.svg",
    "version": "0.2.2",
    "min_server_version": "6.0.0",
    "server": {
        "executables": {
            "linux-amd64": "server/dist/plugin-linux-amd64"
        },
        "executable": ""
    },
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "",
        "footer": "",
        "settings": [],
        "sections": null
    }
}
`);

export default manifest;
