name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black pytest pytest-cov
      - name: Lint with black
        run: black --check app alembic tests
      - name: Run tests with coverage
        run: pytest --cov=app --cov-report=xml --cov-report=term-missing
      - name: Upload coverage to GitHub summary
        if: always()
        run: |
          echo '### Coverage summary' >> $GITHUB_STEP_SUMMARY
          tail -n 20 coverage.xml >> $GITHUB_STEP_SUMMARY 